from pathlib import Path
path = Path('frontend/src/pages/Settings.tsx')
text = path.read_text(encoding='utf-8')
old_block = "                  <Tag color={stage.owner ? 'processing' : 'warning'}>\n                    {stage.owner?.full_name || stage.owner?.username || '待指�?'}\n                  </Tag>\n                </div>\n                {stage.description ? (\n                  <Text className=\"mt-2 block text-sm text-slate-600\">{stage.description}</Text>\n                ) : null}\n                <Divider className=\"!my-3\" />\n                <Form.Item label=\"负责�? name={['stages', stage.key, 'owner_id']}\">\n                  <Select\n                    allowClear\n                    placeholder=\"选择负责�?\n                    options={userOptions}\n                    disabled={savingWorkflow || !userOptions.length}\n                  />\n                </Form.Item>\n                <Form.Item label=\"SLA 描述\" name={['stages', stage.key, 'sla_text']}\">\n                  <Input placeholder=\"例如：T+2 工作日完�?\" />\n                </Form.Item>\n"
new_block = "                  <Tag color={stage.owner ? 'processing' : 'warning'}>\n                    {stage.owner?.full_name || stage.owner?.username || '待指派'}\n                  </Tag>\n                </div>\n                {stage.description ? (\n                  <Text className=\"mt-2 block text-sm text-slate-600\">{stage.description}</Text>\n                ) : null}\n                <Divider className=\"!my-3\" />\n                <Form.Item label=\"负责人\" name={['stages', stage.key, 'owner_id']}>\n                  <Select\n                    allowClear\n                    placeholder=\"选择负责人\"\n                    options={userOptions}\n                    disabled={savingWorkflow || !userOptions.length}\n                    onChange={(value) => {\n                      console.debug(Stage  owner changed:, value)\n                    }}\n                  />\n                </Form.Item>\n                <Form.Item label=\"SLA 描述\" name={['stages', stage.key, 'sla_text']}>\n                  <Input placeholder=\"例如：T+2 工作日完成\" />\n                </Form.Item>\n"
if old_block not in text:
    raise SystemExit('Old block not found')
text = text.replace(old_block, new_block)
path.write_text(text, encoding='utf-8')
