from __future__ import annotations

from typing import List, Dict, Any


DEFAULT_FIELD_CONFIGS: List[Dict[str, Any]] = [
    # 基础信息
    {
        "key": "teacher_code",
        "label": "员工工号",
        "group": "basic",
        "type": "text",
        "width": 130,
        "editable": True,
        "required": True,
        "order_index": 10,
    },
    {
        "key": "name",
        "label": "姓名",
        "group": "basic",
        "type": "text",
        "width": 110,
        "editable": True,
        "required": True,
        "order_index": 20,
    },
    {
        "key": "department",
        "label": "部门",
        "group": "basic",
        "type": "select",
        "width": 120,
        "editable": True,
        "options": ["小学部", "初中部", "高中部", "行政部"],
        "order_index": 30,
    },
    {
        "key": "position",
        "label": "职务",
        "group": "basic",
        "type": "text",
        "width": 120,
        "editable": True,
        "order_index": 40,
    },
    {
        "key": "gender",
        "label": "性别",
        "group": "basic",
        "type": "select",
        "width": 80,
        "editable": True,
        "options": ["男", "女"],
        "order_index": 50,
    },
    {
        "key": "age",
        "label": "年龄",
        "group": "basic",
        "type": "number",
        "width": 80,
        "editable": False,
        "order_index": 60,
    },
    {
        "key": "nation",
        "label": "民族",
        "group": "basic",
        "type": "text",
        "width": 100,
        "editable": True,
        "order_index": 70,
    },
    {
        "key": "political_status",
        "label": "政治面貌",
        "group": "basic",
        "type": "select",
        "width": 120,
        "editable": True,
        "options": ["中共党员", "共青团员", "民主党派", "群众"],
        "order_index": 80,
    },
    {
        "key": "id_number",
        "label": "身份证号码",
        "group": "basic",
        "type": "text",
        "width": 180,
        "editable": True,
        "order_index": 90,
    },
    {
        "key": "birthplace",
        "label": "籍贯",
        "group": "basic",
        "type": "text",
        "width": 120,
        "editable": True,
        "order_index": 100,
    },
    # 合同信息
    {
        "key": "entry_date",
        "label": "入职日期",
        "group": "employment",
        "type": "date",
        "width": 120,
        "editable": True,
        "order_index": 110,
    },
    {
        "key": "regular_date",
        "label": "转正日期",
        "group": "employment",
        "type": "date",
        "width": 120,
        "editable": True,
        "order_index": 120,
    },
    {
        "key": "contract_start",
        "label": "合同开始日",
        "group": "employment",
        "type": "date",
        "width": 120,
        "editable": True,
        "order_index": 130,
    },
    {
        "key": "contract_end",
        "label": "合同到期日",
        "group": "employment",
        "type": "date",
        "width": 120,
        "editable": True,
        "order_index": 140,
    },
    {
        "key": "job_status",
        "label": "在职状态",
        "group": "employment",
        "type": "select",
        "width": 100,
        "editable": True,
        "options": ["在职", "离职", "试用期"],
        "order_index": 150,
    },
    {
        "key": "resign_date",
        "label": "离职日期",
        "group": "employment",
        "type": "date",
        "width": 120,
        "editable": True,
        "order_index": 160,
    },
    {
        "key": "education",
        "label": "最高学历",
        "group": "education",
        "type": "select",
        "width": 120,
        "editable": True,
        "options": ["博士", "硕士", "本科", "专科"],
        "order_index": 170,
    },
    {
        "key": "graduation_school",
        "label": "毕业院校",
        "group": "education",
        "type": "text",
        "width": 150,
        "editable": True,
        "order_index": 180,
    },
    {
        "key": "diploma_no",
        "label": "毕业证号",
        "group": "education",
        "type": "text",
        "width": 150,
        "editable": True,
        "order_index": 190,
    },
    {
        "key": "graduation_date",
        "label": "毕业时间",
        "group": "education",
        "type": "date",
        "width": 120,
        "editable": True,
        "order_index": 200,
    },
    {
        "key": "major",
        "label": "专业",
        "group": "education",
        "type": "text",
        "width": 120,
        "editable": True,
        "order_index": 210,
    },
    {
        "key": "degree",
        "label": "学位",
        "group": "education",
        "type": "text",
        "width": 100,
        "editable": True,
        "order_index": 220,
    },
    {
        "key": "degree_no",
        "label": "学位证号",
        "group": "education",
        "type": "text",
        "width": 150,
        "editable": True,
        "order_index": 230,
    },
    {
        "key": "teacher_cert_type",
        "label": "教师资格种类",
        "group": "qualification",
        "type": "text",
        "width": 150,
        "editable": True,
        "order_index": 240,
    },
    {
        "key": "teacher_cert_no",
        "label": "教师资格证号",
        "group": "qualification",
        "type": "text",
        "width": 180,
        "editable": True,
        "order_index": 250,
    },
    {
        "key": "title_rank",
        "label": "职称等级",
        "group": "qualification",
        "type": "text",
        "width": 120,
        "editable": True,
        "order_index": 260,
    },
    {
        "key": "title_cert_no",
        "label": "职称证号",
        "group": "qualification",
        "type": "text",
        "width": 150,
        "editable": True,
        "order_index": 270,
    },
    {
        "key": "title_cert_date",
        "label": "职称取证时间",
        "group": "qualification",
        "type": "date",
        "width": 120,
        "editable": True,
        "order_index": 280,
    },
    {
        "key": "psychology_cert",
        "label": "心理证",
        "group": "qualification",
        "type": "text",
        "width": 120,
        "editable": True,
        "order_index": 290,
    },
    {
        "key": "certificate_type",
        "label": "持证类别",
        "group": "qualification",
        "type": "text",
        "width": 120,
        "editable": True,
        "order_index": 300,
    },
    {
        "key": "mandarin_level",
        "label": "普通话等级",
        "group": "qualification",
        "type": "text",
        "width": 120,
        "editable": True,
        "order_index": 310,
    },
    {
        "key": "start_work_date",
        "label": "参加工作时间",
        "group": "employment",
        "type": "date",
        "width": 120,
        "editable": True,
        "order_index": 320,
    },
    {
        "key": "teaching_years",
        "label": "教龄",
        "group": "employment",
        "type": "number",
        "width": 80,
        "editable": False,
        "order_index": 330,
    },
    {
        "key": "teaching_grade",
        "label": "任教年级",
        "group": "employment",
        "type": "text",
        "width": 120,
        "editable": True,
        "order_index": 340,
    },
    {
        "key": "teaching_subject",
        "label": "任教学科",
        "group": "employment",
        "type": "text",
        "width": 120,
        "editable": True,
        "order_index": 350,
    },
    {
        "key": "last_work",
        "label": "上一份工作经历",
        "group": "employment",
        "type": "text",
        "width": 200,
        "editable": True,
        "order_index": 360,
    },
    {
        "key": "phone_number",
        "label": "电话号码",
        "group": "contact",
        "type": "text",
        "width": 130,
        "editable": True,
        "order_index": 370,
    },
    {
        "key": "address",
        "label": "家庭住址",
        "group": "contact",
        "type": "text",
        "width": 200,
        "editable": True,
        "order_index": 380,
    },
    {
        "key": "emergency_contact",
        "label": "紧急联系人",
        "group": "contact",
        "type": "text",
        "width": 120,
        "editable": True,
        "order_index": 390,
    },
    {
        "key": "emergency_phone",
        "label": "联系电话",
        "group": "contact",
        "type": "text",
        "width": 130,
        "editable": True,
        "order_index": 400,
    },
    {
        "key": "remarks",
        "label": "备注",
        "group": "other",
        "type": "text",
        "width": 200,
        "editable": True,
        "order_index": 410,
    },
    {
        "key": "ocr_confidence",
        "label": "OCR置信度",
        "group": "other",
        "type": "number",
        "width": 120,
        "editable": False,
        "order_index": 420,
    },
]


